### ISSUE TITLE
K14 Symbolize domain issue

### ISSUE THREAD

**Issue by SofiBar** [ncarboni/vir#1]
As you show in the [graphical overview](https://ncarboni.github.io/vir/#graphicaloverview) (figure 2), the K14 symbolize property should allow expressing the symbolic value of an IC10 Attribute instance. Moreover, this property is cited among [IC10](https://ncarboni.github.io/vir/#IC10_Attribute) class properties. However, K14 domain doesn’t include IC10 class, because the domain is IC9 Representation. Since both IC9 and IC10 are subclasses of E36 Visual Item, the K14 property domain doesn’t include the latter. Therefore, if the property domain is respected, K14 cannot relate an IC10 attribute to an E90 Symbolic Object, despite the graphical overview and IC10 class descriptions. 
Would you mind to extend the K14 property domain to IC10 attribute, so it can be used both with IC9 representation and IC10 attribute instances? 
Thank you

**Comment by ncarboni** [comment]
Indeed, I corrected the mistake. Thanks for pointing it out!

I changed the domain of K14 symbolize to the class 'E36 Visual Item' from CIDOC-CRM (super class of both IC9 Representation and IC10 Attribute), therefore it can be used with both classes.

Changed in:

- documentation
- XML/TTL/NT versions

**Comment by SofiBar** [comment]
Thank you!
